'\" t
.\"     Title: lastlog
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 09/05/2010
.\"    Manual: Команды управления системой
.\"    Source: Команды управления системой
.\"  Language: Russian
.\"
.TH "lastlog" "8" "09/05/2010" "Команды управления системой" "Команды управления системой"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВАНИЕ"
lastlog \- выводит отчёт о последней регистрации в системе всех или указанного пользователя
.SH "СИНТАКСИС"
.HP \w'\fBlastlog\fR\ 'u
\fBlastlog\fR [\fIпараметры\fR]
.SH "ОПИСАНИЕ"
.PP
Программа
\fBlastlog\fR
упорядочивает и выводит содержимое файла
/var/log/lastlog, который содержит даты последнего входа пользователей систему\&. Выводятся
\fIимя пользователя\fR,
\fIпорт\fR
и
\fIдата последнего входа в систему\fR\&. По умолчанию (вызов без параметров) показываются записи файла lastlog, отсортированные согласно расположению пользователей в файле
/etc/passwd\&.
.SH "ПАРАМЕТРЫ"
.PP
Параметры команды
\fBlastlog\fR:
.PP
\fB\-b\fR, \fB\-\-before\fR\fIДНЕЙ\fR
.RS 4
Показать записи lastlog за последние
\fIДНЕЙ\fR\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Показать краткую справку и закончить работу\&.
.RE
.PP
\fB\-t\fR, \fB\-\-time\fR\fIДНЕЙ\fR
.RS 4
Показать записи lastlog новее чем
\fIДНЕЙ\fR\&.
.RE
.PP
\fB\-u\fR, \fB\-\-user\fR \fILOGIN\fR|\fIRANGE\fR
.RS 4
Print the lastlog record of the specified user(s)\&.
.sp
The users can be specified by a login name, a numerical user ID, or a
\fIRANGE\fR
of users\&. This
\fIRANGE\fR
of users can be specified with a min and max values (\fIUID_MIN\-UID_MAX\fR), a max value (\fI\-UID_MAX\fR), or a min value (\fIUID_MIN\-\fR)\&.
.RE
.PP
Если пользователь никогда не регистрировался в системе, то будет показано сообщение
\fI** Никогда не входил в систему**\fR
вместо названия порта и даты\&.
.PP
Only the entries for the current users of the system will be displayed\&. Other entries may exist for users that were deleted previously\&.
.SH "ЗАМЕЧАНИЕ"
.PP
Файл
lastlog
содержит информацию о последней регистрации в системе каждого пользователя\&. Вы не должны применять к нему ротацию журнальных файлов\&. Этот файл является разреженным, поэтому его размер на диске гораздо меньше, чем показывает команда "\fBls \-l\fR" (которая может показывать, что это очень большой файл, если значения идентификаторов пользователей в системе достигают больших значений)\&. Чтобы увидеть реальный размер введите "\fBls \-s\fR"\&.
.SH "ФАЙЛЫ"
.PP
/var/log/lastlog
.RS 4
содержит список завершённых сеансов работы с системой
.RE
.SH "ПРЕДОСТЕРЕЖЕНИЯ"
.PP
Большие промежутки в значениях идентификаторов пользователей приводят к тому, что программа некоторое время ничего не выводит на экран (то есть, если в базе данных lastlog нет пользователей с идентификаторами с 170 по 800, то во время обработки UID с 171 по 799 программа кажется повисшей)\&.
