'\" t
.\"     Title: login.access
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 09/05/2010
.\"    Manual: Форматы файлов
.\"    Source: Форматы файлов
.\"  Language: Russian
.\"
.TH "login\&.access" "5" "09/05/2010" "Форматы файлов" "Форматы файлов"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВАНИЕ"
login.access \- файл контроля доступа в систему
.SH "ОПИСАНИЕ"
.PP
В файле
\fIlogin\&.access\fR
определяются комбинации (пользователь, хост) и/или (пользователь, терминал), которым будет разрешён или запрещён вход в систему\&.
.PP
Когда кто\-то пытается войти в систему выполняется сканирование файла
\fIlogin\&.access\fR
в поисках первой совпадающей записи (пользователь, хост), или в случае не сетевого входа, первой совпадающей записи (пользователь, терминал)\&. Из найденной записи выбирается поле прав доступа, по которому определяется разрешать ли данной учётной записи вход в систему или нет\&.
.PP
Каждая строка таблицы контроля доступа в систему состоит из трёх полей разделённых символом ":" и выглядит так:
.PP
\fIправа_доступа\fR:\fIпользователи\fR:\fIисточники\fR
.PP
Первое поле должно содержать символ "\fI+\fR" (доступ разрешён) или "\fI\-\fR" (доступ запрещён)\&. Второе поле должно содержать имя одной или более учётных записей, имена групп или
\fIALL\fR
(всегда совпадает)\&. Третье поле должно содержать одно или нескольких имён терминалов (для доступа не из сети), имена хостов, доменных имён (начинаются с "\&."), адреса хостов, адреса подсетей (заканчиваются на "\&."),
\fIALL\fR
(всегда совпадает) или
\fILOCAL\fR
(любая строка, не содержащая символа "\&.")\&. Если используется NIS, то также можно использовать @имя_сетевой_группы в шаблонах хостов или именах пользователей\&.
.PP
Оператор
\fIEXCEPT\fR
помогает в написании компактных правил\&.
.PP
Поиск в файле групп производится только когда имя не совпадает с регистрирующимся пользователем\&. Рассматриваются группы только с явно прописанными в них пользователями: программа не принимает во внимание значение первичной группы пользователя\&.
.SH "ФАЙЛЫ"
.PP
/etc/login\&.defs
.RS 4
содержит конфигурацию подсистемы теневых паролей
.RE
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBlogin\fR(1)\&.
