'\" t
.\"     Title: groupadd
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 05/09/2010
.\"    Manual: Commandes de gestion du syst\(`eme
.\"    Source: Commandes de gestion du syst\(`eme
.\"  Language: French
.\"
.TH "GROUPADD" "8" "05/09/2010" "Commandes de gestion du syst\(`em" "Commandes de gestion du syst\(`em"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NOM"
groupadd \- Cr\('eer un nouveau groupe
.SH "SYNOPSIS"
.HP \w'\fBgroupadd\fR\ 'u
\fBgroupadd\fR [\fIoptions\fR] \fIgroupe\fR
.SH "DESCRIPTION"
.PP
The
\fBgroupadd\fR
command creates a new group account using the values specified on the command line plus the default values from the system\&. The new group will be entered into the system files as needed\&.
.SH "OPTIONS"
.PP
Les options disponibles pour la commande
\fBgroupadd\fR
sont\ \&:
.PP
\fB\-f\fR, \fB\-\-force\fR
.RS 4
This option causes the command to simply exit with success status if the specified group already exists\&. When used with
\fB\-g\fR, and the specified GID already exists, another (unique) GID is chosen (i\&.e\&.
\fB\-g\fR
is turned off)\&.
.RE
.PP
\fB\-g\fR, \fB\-\-gid\fR \fIGID\fR
.RS 4
La valeur num\('erique de l\*(Aqidentifiant du groupe (\(Fo\ \&group ID\ \&\(Fc ou GID)\&. Cette valeur doit \(^etre unique, \(`a moins que l\*(Aqoption
\fB\-o\fR
ne soit utilis\('ee\&. La valeur ne doit pas \(^etre n\('egative\&. Par d\('efaut le plus petit identifiant plus grand que 999 et que les identifiants des groupes existants est utilis\('e\&. Les valeurs comprises entre 0 et 999 sont g\('en\('eralement r\('eserv\('ees aux comptes syst\(`eme\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Afficher un message d\*(Aqaide et quitter\&.
.RE
.PP
\fB\-K\fR, \fB\-\-key\fR \fICL\('E\fR=\fIVALEUR\fR
.RS 4
Surcharger les valeurs par d\('efaut du fichier
/etc/login\&.defs
(GID_MIN, GID_MAX et autres)\&. L\*(Aqoption
\fB\-K\fR
peut \(^etre indiqu\('ee plusieurs fois\&.
.sp
Exemple\ \&:
\fB\-K\fR
\fIGID_MIN\fR=\fI10\fR
\fB\-K\fR
\fIGID_MAX\fR=\fI499\fR
.sp
Note\ \&:
\fB\-K\fR
\fIGID_MIN\fR=\fI10\fR,\fIGID_MAX\fR=\fI499\fR
ne fonctionne pas pour l\*(Aqinstant\&.
.RE
.PP
\fB\-o\fR, \fB\-\-non\-unique\fR
.RS 4
This option permits to add a group with a non\-unique GID\&.
.RE
.PP
\fB\-p\fR, \fB\-\-password\fR \fIMOT_DE_PASSE\fR
.RS 4
Le mot de passe chiffr\('e, comme renvoy\('e par
\fBcrypt\fR(3)\&. Le comportement par d\('efaut est de d\('esactiver le mot de passe\&.
.sp
\fBNote:\fR
l\*(Aqutilisation de cette option est d\('econseill\('ee car le mot de passe (ou le mot de passe chiffr\('e) peut \(^etre visible des utilisateurs qui affichent la liste des processus\&.
.sp
Il est n\('ecessaire de v\('erifier si le mot de passe respecte la politique de mots de passe du syst\(`eme\&.
.RE
.PP
\fB\-r\fR, \fB\-\-system\fR
.RS 4
Cr\('eer un groupe syst\(`eme\&.
.sp
The numeric identifiers of new system groups are chosen in the
\fBSYS_GID_MIN\fR\-\fBSYS_GID_MAX\fR
range, defined in
login\&.defs, instead of
\fBGID_MIN\fR\-\fBGID_MAX\fR\&.
.RE
.SH "CONFIGURATION"
.PP
Les variables de configuration suivantes de
/etc/login\&.defs
modifient le comportement de cet outil\ \&:
.PP
\fBGID_MAX\fR (nombre), \fBGID_MIN\fR (nombre)
.RS 4
Plage d\*(Aqidentifiants num\('eriques de groupes que les commandes
\fBuseradd\fR,
\fBgroupadd\fR
ou
\fBnewusers\fR
peuvent utiliser pour la cr\('eation des groupes normaux\&.
.RE
.PP
\fBMAX_MEMBERS_PER_GROUP\fR (nombre)
.RS 4
Nombre maximum de membres par entr\('ee de groupe\&. Lorsque le maximum est atteint, une nouvelle entr\('ee de groupe (ligne) est d\('emarr\('ee dans
/etc/group
(avec le m\(^eme nom, m\(^eme mot de passe, et m\(^eme GID)\&.
.sp
La valeur par d\('efaut est 0, ce qui signifie qu\*(Aqil n\*(Aqy a pas de limites pour le nombre de membres dans un groupe\&.
.sp
Cette fonctionnalit\('e (groupe d\('ecoup\('e) permet de limiter la longueur des lignes dans le fichier de groupes\&. Ceci est utile pour s\*(Aqassurer que les lignes pour les groupes NIS ne sont pas plus grandes que 1024 caract\(`eres\&.
.sp
Si vous avez besoin de fixer cette limite, vous pouvez utiliser 25\&.
.sp
Remarque\ \&: les groupes d\('ecoup\('es ne sont peut\-\(^etre pas pris en charge par tous les outils (m\(^eme dans la suite d\*(Aqoutils Shadow)\&. Vous ne devriez pas utiliser cette variable, sauf si vous en avez vraiment besoin\&.
.RE
.PP
\fBSYS_GID_MAX\fR (nombre), \fBSYS_GID_MIN\fR (nombre)
.RS 4
Plage d\*(Aqidentifiants num\('eriques de groupes que les commandes
\fBuseradd\fR,
\fBgroupadd\fR
ou
\fBnewusers\fR
peuvent utiliser pour la cr\('eation de groupes syst\(`eme\&.
.RE
.SH "FICHIERS"
.PP
/etc/group
.RS 4
Informations sur les groupes\&.
.RE
.PP
/etc/gshadow
.RS 4
Informations s\('ecuris\('ees sur les groupes\&.
.RE
.PP
/etc/login\&.defs
.RS 4
Configuration de la suite des mots de passe cach\('es \(Fo\ \&shadow password\ \&\(Fc\&.
.RE
.SH "AVERTISSEMENTS"
.PP
Les noms de groupe doivent commencer par une lettre minuscule ou un tiret bas (\(Fo\ \&underscore\ \&\(Fc), et seuls des lettres minuscules, des chiffres, des \(Fo\ \&underscore\ \&\(Fc, ou des tirets peuvent suivre\&. Ils peuvent se terminer par un signe dollar\&. Soit, sous la forme d\*(Aqune expression rationnelle\ \&: [a\-z_][a\-z0\-9_\-]*[$]?
.PP
Les noms de groupe sont limit\('es \(`a 16 caract\(`eres\&.
.PP
You may not add a NIS or LDAP group\&. This must be performed on the corresponding server\&.
.PP
If the groupname already exists in an external group database such as NIS or LDAP,
\fBgroupadd\fR
will deny the group creation request\&.
.SH "VALEURS DE RETOUR"
.PP
La commande
\fBgroupadd\fR
retourne les valeurs suivantes en quittant\ \&:
.PP
\fI0\fR
.RS 4
succ\(`es
.RE
.PP
\fI2\fR
.RS 4
erreur de syntaxe
.RE
.PP
\fI3\fR
.RS 4
param\(`etre non valable pour l\*(Aqoption
.RE
.PP
\fI4\fR
.RS 4
GID d\('ej\(`a utilis\('e (et
\fB\-o\fR
n\*(Aqest pas utilis\('e)
.RE
.PP
\fI9\fR
.RS 4
nom de groupe d\('ej\(`a utilis\('e
.RE
.PP
\fI10\fR
.RS 4
impossible de mettre \(`a jour le fichier des groupes
.RE
.SH "VOIR AUSSI"
.PP
\fBchfn\fR(1),
\fBchsh\fR(1),
\fBpasswd\fR(1),
\fBgpasswd\fR(8),
\fBgroupdel\fR(8),
\fBgroupmod\fR(8),
\fBlogin.defs\fR(5),
\fBuseradd\fR(8),
\fBuserdel\fR(8),
\fBusermod\fR(8)\&.
