'\" t
.\"     Title: vipw
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 05-09-2010
.\"    Manual: Systemhanteringskommandon
.\"    Source: Systemhanteringskommandon
.\"  Language: Swedish
.\"
.TH "VIPW" "8" "05-09-2010" "Systemhanteringskommandon" "Systemhanteringskommandon"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAMN"
vipw, vigr \- redigera l\(:osenordet, grupp, skuggl\(:osenord eller skuggruppfil
.SH "SYNOPSIS"
.HP \w'\fBvipw\fR\ 'u
\fBvipw\fR [\fIflaggor\fR]
.HP \w'\fBvigr\fR\ 'u
\fBvigr\fR [\fIflaggor\fR]
.SH "BESKRIVNING"
.PP
The
\fBvipw\fR
and
\fBvigr\fR
commands edits the files
/etc/passwd
and
/etc/group, respectively\&. With the
\fB\-s\fR
flag, they will edit the shadow versions of those files,
/etc/shadow
and
/etc/gshadow, respectively\&. The programs will set the appropriate locks to prevent file corruption\&. When looking for an editor, the programs will first try the environment variable
\fB$VISUAL\fR, then the environment variable
\fB$EDITOR\fR, and finally the default editor,
\fBvi\fR(1)\&.
.SH "FLAGGOR"
.PP
Flaggorna som g\(:aller f\(:or kommandona
\fBvipw\fR
och
\fBvigr\fR
\(:ar:
.PP
\fB\-g\fR, \fB\-\-group\fR
.RS 4
Redigera gruppdatabasen\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Visa hj\(:alpmeddelande och avsluta\&.
.RE
.PP
\fB\-p\fR, \fB\-\-passwd\fR
.RS 4
Redigera l\(:osenordsdatabasen\&.
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR
.RS 4
Tyst l\(:age\&.
.RE
.PP
\fB\-s\fR, \fB\-\-shadow\fR
.RS 4
Redigera shadow\- eller gshadow\-databasen\&.
.RE
.SH "ENVIRONMENT"
.PP
\fBVISUAL\fR
.RS 4
Editor to be used\&.
.RE
.PP
\fBEDITOR\fR
.RS 4
Editor to be used if
\fBVISUAL\fR
is not set\&.
.RE
.SH "FILER"
.PP
/etc/group
.RS 4
Gruppkontoinformation\&.
.RE
.PP
/etc/gshadow
.RS 4
S\(:aker gruppkontoinformation\&.
.RE
.PP
/etc/passwd
.RS 4
Anv\(:andarkontoinformation\&.
.RE
.PP
/etc/shadow
.RS 4
S\(:aker anv\(:andarkontoinformation\&.
.RE
.SH "SE OCKS\(oA"
.PP

\fBvi\fR(1),
\fBgroup\fR(5),
\fBgshadow\fR(5)
,
\fBpasswd\fR(5), ,
\fBshadow\fR(5)\&.
