.\" This file Copyright (C) 2001-2005 Jeff Tranter
.\" (tranter@pobox.com)
.\" It may be distributed under the GNU Public License, version 2, or
.\" any higher version. See section COPYING of the GNU Public license
.\" for conditions under which this file may be redistributed.
.TH VOLNAME 1 "13 Nov 2004" "Linux" "User Commands"
.SH NAME
volname \- return volume name
.SH SYNOPSIS
volname [<device-file>]

.SH DESCRIPTION

.B Volname
returns the volume name for a device formatted with an
ISO-9660 file system, typically a CD-ROM. It also works with
normal files that contain a ISO-9660 file system.

The file name can be specified on the command line.  If omitted,
it defaults to /dev/cdrom.

.SH AUTHOR
.B Volname
was written by Jeff Tranter (tranter@pobox.com) and is released
under the conditions of the GNU General Public License. See the file
COPYING and notes in the source code for details.

.SH SEE ALSO

eject(1)
